require 'optparse'
require 'resolv'
require 'svcb_rr_patch'
require 'tttls1.3'

require 'echspec/version'
require 'echspec/utils'
require 'echspec/result'
require 'echspec/spec'
require 'echspec/cli'
